### ISSUE TITLE
Found interface git4idea.repo.GitRepositoryManager, but class was expected

### ISSUE THREAD

**Issue by swaroopch** [jexp/jetbrains-heroku-plugin#15]
Just installed IntelliJ Community Edition 11.1.1 (Build #IC-117.117, Built on March 30, 2012, with JDK 1.6.0_31 on Mac) + Heroku Integration plugin 0.3.8 and got this error:

```
Found interface git4idea.repo.GitRepositoryManager, but class was expected: Found interface git4idea.repo.GitRepositoryManager, but class was expected
java.lang.IncompatibleClassChangeError: Found interface git4idea.repo.GitRepositoryManager, but class was expected
    at com.jetbrains.heroku.git.NewGitRemoteHandler.getRepository(NewGitRemoteHandler.java:59)
    at com.jetbrains.heroku.git.NewGitRemoteHandler.isGitEnabled(NewGitRemoteHandler.java:55)
    at com.jetbrains.heroku.git.GitHelper.isGitEnabled(GitHelper.java:99)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.update(HerokuSetupWindow.java:64)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.createContentPane(HerokuSetupWindow.java:54)
    at com.jetbrains.heroku.ui.HerokuToolWindow.<init>(HerokuToolWindow.java:40)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.<init>(HerokuSetupWindow.java:224)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindow(HerokuToolWindowFactory.java:43)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindowContent(HerokuToolWindowFactory.java:34)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:445)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11$1.run(ToolWindowManagerImpl.java:500)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
    at java.awt.EventQueue.access$000(EventQueue.java:85)
    at java.awt.EventQueue$1.run(EventQueue.java:643)
    at java.awt.EventQueue$1.run(EventQueue.java:641)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:652)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:420)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by jexp** [comment]
Thanks, will look into it, seems that they've changed the API in an incompatible way within a minor version :(

**Comment by swaroopch** [comment]
Wow, thanks for the super-fast reply @jexp :)

> Thanks, will look into it, seems that they've changed the API in an incompatible way within a minor version :(

:(
