### ISSUE TITLE
Error when trying to Attach to project

### ISSUE THREAD

**Issue by astocks** [jexp/jetbrains-heroku-plugin#25]
10:08:33 PM NoSuchMethodError: Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.jetbrains.heroku.ui.JBBackgroundAction$1@1d2447f7,notifier=null,catchExceptions=false,when=1370657313851] on sun.awt.X11.XToolkit@70971f8f: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V

**Comment by jexp** [comment]
What version of what Jetbrains product are you using?

**Comment by astocks** [comment]
Rubymine 5.4.2

**Comment by EddieDee** [comment]
Same thing is happening to me, with the exact same version of RubyMine and windows 8

**Comment by saintd** [comment]
"Create and Attach Heroku Application" and "Attach to existing Heroku Application" causes this error:

`Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.jetbrains.heroku.ui.JBBackgroundAction$1@1784b78,notifier=null,catchExceptions=false,when=1372020620777] on sun.awt.windows.WToolkit@16d43cd: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
java.lang.NoSuchMethodError: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
    at com.jetbrains.heroku.git.GitHelper.addHerokuRemote(GitHelper.java:51)
    at com.jetbrains.heroku.git.GitHelper.attachRemote(GitHelper.java:160)
    at com.jetbrains.heroku.ui.HerokuSetupWindow$3.runActionPerformed(HerokuSetupWindow.java:170)
    at com.jetbrains.heroku.ui.JBBackgroundAction$1.run(JBBackgroundAction.java:30)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:721)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:691)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)`

Rubymine 5.4.2, win7.

**Comment by nameinane** [comment]
Same issue.  Webstorm 6.0.2 (macos).

**Comment by Hrant-Khachatrian** [comment]
Same: PhpStorm 6.0.3

**Comment by KoljaTM** [comment]
Still experiencing this issue with Intellij Idea Community edition 12.1.4 and plugin version 0.4.2
Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.jetbrains.heroku.ui.JBBackgroundAction$1@f27946,notifier=null,catchExceptions=false,when=1375541294244] on sun.awt.windows.WToolkit@116d55f: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V

**Comment by henriquecf** [comment]
It is still happening to me too. I'm using Pycharm 2.7.3 and version 0.4.3 of the plugin

**Comment by jexp** [comment]
@henriquecf @KoljaTM With 0.4.3 ?

**Comment by henriquecf** [comment]
Yeah. I just upgraded it

**Comment by henriquecf** [comment]
And my error is not only while attaching. While creating a new app too.

**Comment by jexp** [comment]
@henriquecf What is the exact error message / stack trace?

Sorry for all the mess but the open-api is really horrible in terms of compatibility between different versions. So far I have to cater for 4 different API versions of the git plugin :(

**Comment by jproby** [comment]
I have the same problem sorry ;-)  (plugin 0.4.3 - PyCharm 2.7.3) here is the full stack trace : 

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.jetbrains.heroku.ui.JBBackgroundAction$1@7909c16f,notifier=null,catchExceptions=false,when=1378719409202] on apple.awt.CToolkit@189a34e4: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
java.lang.NoSuchMethodError: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
    at com.jetbrains.heroku.git.GitHelper.addHerokuRemote(GitHelper.java:51)
    at com.jetbrains.heroku.git.GitHelper.attachRemote(GitHelper.java:160)
    at com.jetbrains.heroku.ui.HerokuSetupWindow$2.runActionPerformed(HerokuSetupWindow.java:142)
    at com.jetbrains.heroku.ui.JBBackgroundAction$1.run(JBBackgroundAction.java:30)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by casualuser** [comment]
the same here attaching to existing with webstorm 7 eap at macos

is there workaround at the moment?

git4idea.commands.GitSimpleHandler.setNoSSH(Z)V: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
java.lang.NoSuchMethodError: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
    at com.jetbrains.heroku.git.GitHelper.addHerokuRemote(GitHelper.java:51)
    at com.jetbrains.heroku.git.GitHelper.attachRemote(GitHelper.java:160)
    at com.jetbrains.heroku.ui.HerokuSetupWindow$2.runActionPerformed(HerokuSetupWindow.java:142)
    at com.jetbrains.heroku.ui.JBBackgroundAction$1.run(JBBackgroundAction.java:30)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by jexp** [comment]
I try to look into it again. All these incompatible OpenAPI changes :(

**Comment by mvgijssel** [comment]
Not to get on your nerves, love the plugin :), but also the same problem:

Rubymine 6.0.1
Heroku 0.4.3

git4idea.commands.GitSimpleHandler.setNoSSH(Z)V: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
java.lang.NoSuchMethodError: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
    at com.jetbrains.heroku.git.GitHelper.addHerokuRemote(GitHelper.java:51)
    at com.jetbrains.heroku.git.GitHelper.attachRemote(GitHelper.java:160)
    at com.jetbrains.heroku.ui.HerokuSetupWindow$2.runActionPerformed(HerokuSetupWindow.java:142)
    at com.jetbrains.heroku.ui.JBBackgroundAction$1.run(JBBackgroundAction.java:30)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by maestrofjp** [comment]
PyCharm: 3.4.1 (Linux)
Git Integration: 8.1

```
git4idea.commands.GitSimpleHandler.setNoSSH(Z)V: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
java.lang.NoSuchMethodError: git4idea.commands.GitSimpleHandler.setNoSSH(Z)V
    at com.jetbrains.heroku.git.GitHelper.addHerokuRemote(GitHelper.java:51)
    at com.jetbrains.heroku.git.GitHelper.attachRemote(GitHelper.java:160)
    at com.jetbrains.heroku.ui.HerokuSetupWindow$2.runActionPerformed(HerokuSetupWindow.java:142)
    at com.jetbrains.heroku.ui.JBBackgroundAction$1.run(JBBackgroundAction.java:30)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
