### ISSUE TITLE
Unsupported major.minor version exception in RubyMine

### ISSUE THREAD

**Issue by thejoecarroll** [jexp/jetbrains-heroku-plugin#26]
After I upgraded RubyMine to the current version, 5.4.3.2.1 the plugin stopped working and causes an exception upon starting up the IDE:

```

Stopped working after upgrading RubyMine to v 5.4.3.2.1. The plugin causes an exception on startup with the following error log:

com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]: com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]
com.intellij.diagnostic.PluginException: com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:108)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.wm.ToolWindowEP.getFactoryClass(ToolWindowEP.java:85)
    at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:72)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow(ToolWindowManagerImpl.java:491)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.f(ToolWindowManagerImpl.java:470)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$1800(ToolWindowManagerImpl.java:86)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$9.run(ToolWindowManagerImpl.java:443)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:264)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:179)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$4$2.run(ProjectManagerImpl.java:435)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:153)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:149)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:125)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:102)
    ... 31 more
```

**Comment by 10257** [comment]
Got the same issue in IntelIJ IDEA IU-129.161

```
10:34:42 PluginException: com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]: com/jetbrains/heroku/ui/HerokuToolWindowFactory : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]
23:27:25 PluginException: com/jetbrains/heroku/HerokuSettings : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]: com/jetbrains/heroku/HerokuSettings : Unsupported major.minor version 51.0 [Plugin: Heroku Integration]
```

**Comment by marks** [comment]
I am pretty sure this has to do with line 10 of `plugin.xml` (link: https://github.com/jexp/jetbrains-heroku-plugin/blob/master/META-INF/plugin.xml#L10) but having never written an IntelliJ/RubyMine plugin, I dont know what that build # corresponds to.

My RubyMine version is 5.4.3.2.1 / Build #RM-129.861

**Comment by marks** [comment]
Update: There are a list of build numbers and what they mean at http://confluence.jetbrains.com/display/IDEADEV/Build+Number+Ranges

Bottom line, this plugin should start working if you just edit the plugin.xml file with a larger build # and re-install. I'll try doing this later

**Comment by jexp** [comment]
Sorry it took so long. Uploaded version 0.4.3 which should fix the incompatible class error, due to compilation with wrong JDK with IDEA 13, sorry for that!

@thejoecarroll @kr0hmy @marks please try it out and report back.
