### ISSUE TITLE
Error loading Heroku plugin

### ISSUE THREAD

**Issue by belskihvv** [jexp/jetbrains-heroku-plugin#31]
Hello.

When I open the Project Settings dialog in Rubymine 6.3:
[ 191063]  ERROR - openapi.options.ConfigurableEP - com/heroku/api/exception/RequestFailedException 
java.lang.NoClassDefFoundError: com/heroku/api/exception/RequestFailedException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.a(ServiceManagerImpl.java:128)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentImplementation(ServiceManagerImpl.java:121)
        at org.picocontainer.defaults.BasicComponentParameter.resolveAdapter(BasicComponentParameter.java:108)
        at org.picocontainer.defaults.BasicComponentParameter.isResolvable(BasicComponentParameter.java:71)
        at org.picocontainer.defaults.ComponentParameter.isResolvable(ComponentParameter.java:122)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:162)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
        at com.intellij.openapi.options.ConfigurableEP$NewInstanceFactory.create(ConfigurableEP.java:192)
        at com.intellij.openapi.options.ConfigurableEP$NewInstanceFactory.create(ConfigurableEP.java:190)
        at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:150)
        at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:54)
        at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:53)
        at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:204)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:65)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:54)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:63)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:923)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
        at java.awt.Component.processMouseEvent(Component.java:6505)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
        at java.awt.Component.processEvent(Component.java:6270)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4861)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:708)
        at java.awt.EventQueue$4.run(EventQueue.java:706)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: com.heroku.api.exception.RequestFailedException PluginClassLoader[Heroku Integration, 0.4.3]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 66 more
[ 191080]  ERROR - openapi.options.ConfigurableEP - RubyMine 6.3  Build #RM-135.588 
[ 191080]  ERROR - openapi.options.ConfigurableEP - JDK: 1.7.0_55 
[ 191081]  ERROR - openapi.options.ConfigurableEP - VM: OpenJDK 64-Bit Server VM 
[ 191081]  ERROR - openapi.options.ConfigurableEP - Vendor: Oracle Corporation 
[ 191085]  ERROR - openapi.options.ConfigurableEP - OS: Linux 
[ 191085]  ERROR - openapi.options.ConfigurableEP - Last Action: ShowSettings

**Comment by leompeters** [comment]
+1
